// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiSO8yI126LAvvozdeMJrpPE-m1vfgm1E',
    appId: '1:735183806178:web:4428732da3869efc7b88bb',
    messagingSenderId: '735183806178',
    projectId: 'microblogging-app-121c9',
    authDomain: 'microblogging-app-121c9.firebaseapp.com',
    storageBucket: 'microblogging-app-121c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTOi4bwe6usoIP93Joj1XEa2f2SiXt37s',
    appId: '1:735183806178:android:5ea5be21a80d15087b88bb',
    messagingSenderId: '735183806178',
    projectId: 'microblogging-app-121c9',
    storageBucket: 'microblogging-app-121c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCll-NuT1SM00VrahBTTxcxcmWLibmKu4',
    appId: '1:735183806178:ios:a9faf0bcbfea028b7b88bb',
    messagingSenderId: '735183806178',
    projectId: 'microblogging-app-121c9',
    storageBucket: 'microblogging-app-121c9.firebasestorage.app',
    iosBundleId: 'com.example.nest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCll-NuT1SM00VrahBTTxcxcmWLibmKu4',
    appId: '1:735183806178:ios:a9faf0bcbfea028b7b88bb',
    messagingSenderId: '735183806178',
    projectId: 'microblogging-app-121c9',
    storageBucket: 'microblogging-app-121c9.firebasestorage.app',
    iosBundleId: 'com.example.nest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiSO8yI126LAvvozdeMJrpPE-m1vfgm1E',
    appId: '1:735183806178:web:f56a6f45b9730e9b7b88bb',
    messagingSenderId: '735183806178',
    projectId: 'microblogging-app-121c9',
    authDomain: 'microblogging-app-121c9.firebaseapp.com',
    storageBucket: 'microblogging-app-121c9.firebasestorage.app',
  );
}
